version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env.db  # Loads database credentials
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  auth_service:
    build: 
      context: ./auth_service
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - app_network
    env_file:
      - .env.db  # Provides database credentials to Django settings

  institutes_service:
    build:
      context: ./institutes_service
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - app_network
    env_file:
      - .env.db

  courses_service:
    build:
      context: ./courses_service
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - app_network
    env_file:
      - .env.db

  resources_service:
    build:
      context: ./resources_service
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - app_network
    env_file:
      - .env.db

  frontend:
    build: 
      context: ./frontend_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth_service
      - institutes_service
      - courses_service
      - resources_service
    networks:
      - app_network
    env_file:
      - .env  # Loads frontend environment variables

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
