# Generated by Django 5.1.2 on 2024-10-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_alter_institute_description_alter_institute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
