# Generated by Django 5.1.2 on 2024-12-09 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_code'),
        ('institutes', '0003_alter_institute_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='institute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.institute'),
        ),
    ]
