# Generated by Django 5.1.2 on 2025-02-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('institute_id', models.IntegerField()),
            ],
        ),
    ]
