# Generated by Django 5.1.2 on 2024-10-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('course_id', models.IntegerField()),
                ('posted_by', models.IntegerField()),
                ('resource_type', models.CharField(max_length=100)),
            ],
        ),
    ]
